name = "zendev-docs"
compatibility_date = "2026-09-03"
workers_dev = true

[[routes]]
pattern = "docs.zendev.zrr.dev"
custom_domain = true

[assets]
directory = "./site"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
