name: CD - Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: cloudflare-documentation
  cancel-in-progress: false

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || vars.CLOUDFLARE_DEPLOY_ENABLED == 'true'
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff # v6
        with:
          enable-cache: false

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.14"

      - name: Build documentation
        run: uv run --locked --group docs zensical build --clean --strict

      - name: Deploy to Cloudflare Workers
        id: deploy
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --strict
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "4.128.0"
